### ISSUE TITLE
[Design] 그룹 커버 이미지 PlaceHolder 관련

### ISSUE THREAD

**Issue by nahy-512** [UMC-Project-Namo/Android#201]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Todo**

- [ ] 이미지가 로드되고 있을 때 회색 동그라미
- [ ] 이미지가 유효하지 않을 때 몽이 이미지
