### ISSUE TITLE
[Feat] 버전 확인 및 업데이트 요청 추가

### ISSUE THREAD

**Issue by edv-Shin** [UMC-Project-Namo/Android#215]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 앱 진입 시에 버전 확인
- 최소 버전 미만일 경우 업데이트 요청 후 마켓 이동

## **Todo**

- [ ] 앱 진입 시에 버전 확인
- [ ] 최소 버전 미만일 경우 업데이트 요청 후 마켓 이동
