### ISSUE TITLE
[Refactor] 카카오맵 v2로 버전 업데이트

### ISSUE THREAD

**Issue by nahy-512** [UMC-Project-Namo/Android#232]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 카카오맵 구 SDK가 6/30에 지원 종료됨에 따라 신규 SDK로 변경합니다.

## **Todo**

- [x] 신규 SDK로 변경
- 장소 선택 로직 변경
  - [x] 뒤로가기 버튼 추가
  - [x] 장소 편집인 경우 장소 아이템 표시
  - [x] 아이템 우측에 선택된 아이템 체크 표시
  - [x] 취소 버튼 클릭 시 뒤로가기 -> 장소 선택 취소 동작

## **Reference(Optional)**

- [카카오맵 Android/iOS 용 구. SDK 종료 예정 (2024년 6월 30일(일)) 안내](https://devtalk.kakao.com/t/android-ios-sdk-2024-6-30/134180)
- [관련 QA](https://www.notion.so/namo-log/bdddeef2c55a4e54a8c461c09c0225d8?pvs=4)
