### ISSUE TITLE
[Fix] 캘린더 말줄임표 삭제, 캘린더 이모지 사용 대처

### ISSUE THREAD

**Issue by edv-Shin** [UMC-Project-Namo/Android#235]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [x] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 캘린더 말줄임표 삭제
- 이모지 사용 시 블럭을 넘어가는 이슈 해결

## **Todo**

- [x] 캘린더 말줄임표 삭제
- [x] 이모지 사용 시 블럭을 넘어가는 이슈 해결
