### ISSUE TITLE
[Refactor] 리소스 정리 및 코드 컨벤션 반영

### ISSUE THREAD

**Issue by nahy-512** [UMC-Project-Namo/Android#239]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 리소스 관련하여 컨벤션을 맞추는 작업을 진행합니다.

## **Todo**

- [x] 쓰이지 않는 리소스 삭제
- [x] 리소스 컨벤션 반영
