### ISSUE TITLE
[Refactor] 캘린더 코드 정리

### ISSUE THREAD

**Issue by edv-Shin** [UMC-Project-Namo/Android#243]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 커스텀 캘린더 클래스 코드 정리
- 개인/그룹 캘린더 코드 정리

## **Todo**

- [ ] 커스텀 캘린더 클래스 코드 정리
- [ ] 개인/그룹 캘린더 코드 정리
