### ISSUE TITLE
[Refactor] 개인 일정 및 카테고리 로컬 기능 사용 중지

### ISSUE THREAD

**Issue by nahy-512** [UMC-Project-Namo/Android#248]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## **Description**

- 룸디비 사용 코드 삭제

## **Todo**

- [ ] 일정
- [ ] 카테고리
